.TH "src/settings Directory Reference" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settings Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_settings\&.c\fP"
.br
.ti -1c
.RI "file \fBft_settings_draw_img\&.c\fP"
.br
.ti -1c
.RI "file \fBft_settings_hooks\&.c\fP"
.br
.ti -1c
.RI "file \fBft_settings_state\&.c\fP"
.br
.in -1c
