.TH "src/render Directory Reference" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdraw_column\&.c\fP"
.br
.ti -1c
.RI "file \fBminimap\&.c\fP"
.br
.ti -1c
.RI "file \fBminimap_player\&.c\fP"
.br
.ti -1c
.RI "file \fBrender\&.c\fP"
.br
.ti -1c
.RI "file \fBrender_more\&.c\fP"
.br
.ti -1c
.RI "file \fBsprite\&.c\fP"
.br
.in -1c
