.TH "src/print Directory Reference" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_print\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_color\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_errors\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_special\&.c\fP"
.br
.in -1c
