.TH "src/generation/arg.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/arg.c
.SH SYNOPSIS
.br
.PP
\fR#include 'maze\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub_parse_generation_arg\fP (char *gen, size_t *width, size_t *height)"
.br
.RI "Parse the argument for generation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
