.TH "src/cub3d.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cub3d.c \- : Main program of the Cub3D  

.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'maze\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub3d\fP (int argc, char **argv)"
.br
.RI "Main function of the cub3d project\&. "
.in -1c
.SH "Detailed Description"
.PP 
: Main program of the Cub3D 


.PP
\fBDate\fP
.RS 4
08 August 2025 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
