.TH "src/cub3d_raoul.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cub3d_raoul.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include 'data_structure\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub3d_init_render\fP (\fBt_data\fP *data)"
.br
.RI "Init cub for rendering\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cub3d_init_render (\fBt_data\fP * data)"

.PP
Init cub for rendering\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 OK, error otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
