.TH "src/render/draw_column.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/draw_column.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdraw_column\fP (\fBt_data\fP *data, int x, const \fBt_raydata\fP *rdata)"
.br
.RI "Draw a column of pixels from a raycast result\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void draw_column (\fBt_data\fP * data, int x, const \fBt_raydata\fP * rdata)"

.PP
Draw a column of pixels from a raycast result\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.br
\fIx\fP x axis column 
.br
\fIrdata\fP structure to handle important values for rendering 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
