.TH "src/filters/filters.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/filters/filters.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'maze\&.h'\fP
.br
\fR#include 'filter\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd_filter\fP (\fBt_img\fP *img, int filter)"
.br
.ti -1c
.RI "void \fBadd_filter_protected\fP (\fBt_img\fP *img, int filter)"
.br
.ti -1c
.RI "void \fBadd_tint\fP (\fBt_img\fP *img, unsigned char red_add, unsigned char green_add, unsigned char blue_add)"
.br
.ti -1c
.RI "void \fBadd_tint_protected\fP (\fBt_img\fP *img, unsigned char red_add, unsigned char green_add, unsigned char blue_add)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_filter (\fBt_img\fP * img, int filter)"

.SS "void add_filter_protected (\fBt_img\fP * img, int filter)"

.SS "void add_tint (\fBt_img\fP * img, unsigned char red_add, unsigned char green_add, unsigned char blue_add)"

.SS "void add_tint_protected (\fBt_img\fP * img, unsigned char red_add, unsigned char green_add, unsigned char blue_add)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
