.TH "src/filters/filters-bw.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/filters/filters-bw.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'filter\&.h'\fP
.br
\fR#include 'ft_keys\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'maze\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconvert_textures_to_black_and_white\fP (\fBt_map\fP *map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void convert_textures_to_black_and_white (\fBt_map\fP * map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
