.TH "src/map_verif/ft_file_fill.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_file_fill.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'get_next_line\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBcount_file_lines\fP (char *file_name)"
.br
.RI "Simple function to count the number of lines in a file\&. "
.ti -1c
.RI "char ** \fBread_file_lines\fP (\fBt_map\fP *map, char *map_name)"
.br
.RI "Read the map file line by line and return an array of strings\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
