.TH "src/ft_free_mlx.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_free_mlx.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_mlx_end\fP (\fBt_mlx\fP *mlx)"
.br
.RI "Close and free the mlx structure\&. "
.ti -1c
.RI "void \fBft_free_settings\fP (\fBt_mlx\fP *mlx)"
.br
.RI "Free all the settings variables\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
