.TH "src/ft_mlx/ft_init_mlx.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_mlx/ft_init_mlx.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_mlx_init\fP (\fBt_data\fP *data)"
.br
.RI "Initialize the mlx structure, create settings window, and load game\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
