.TH "src/map_verif/ft_map_check.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_map_check.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_map\fP \fBft_map_check_dimensions\fP (\fBt_map\fP *map, char *map_name)"
.br
.RI "Check the map structure and try to open the map file\&. sets error to -1 if an error occurred\&. "
.ti -1c
.RI "\fBt_map\fP \fBcheck_map_chars_borders\fP (\fBt_map\fP *map)"
.br
.RI "Check if the map has only acceptable characters and if there is borders everywhere, as it should be\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
