.TH "src/map_verif/ft_map_utils.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_map_utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsuppress_newlines\fP (char **lines)"
.br
.RI "Suppress newlines in the given lines\&. "
.ti -1c
.RI "bool \fBis_only_whitespace\fP (const char *str)"
.br
.RI "Check if the string contains only whitespace characters\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
