.TH "src/map_verif/ft_map_boundaries.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_map_boundaries.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_coordinates\fP \fBfind_position\fP (\fBt_map\fP *map, const char *charset)"
.br
.RI "Find the position of the player with charset in the map\&. "
.ti -1c
.RI "int \fBis_walkable\fP (char c)"
.br
.RI "Check if a character is walkable or not\&. "
.ti -1c
.RI "int \fBis_in_bounds\fP (char **map, size_t y, size_t x)"
.br
.RI "Check if a position is in bounds of map or not\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
