.TH "src/print/ft_print.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_print.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_keys\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_print_key\fP (int keycode)"
.br
.RI "Print the keycode name if registered or just its value if not\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
