.TH "src/print/ft_print_color.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_print_color.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_print_color\fP (\fBt_color\fP *color)"
.br
.RI "Print a color\&. "
.ti -1c
.RI "void \fBft_print_floor_ceiling\fP (\fBt_map\fP *map)"
.br
.RI "Print the colors of floor and ceiling\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
