.TH "src/map_verif/ft_search_map.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_search_map.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBfill_map_region\fP (\fBt_map\fP *map)"
.br
.RI "Fill the map region of the file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
