.TH "src/map_verif/ft_search_config.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_verif/ft_search_config.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBis_config_line\fP (char *line)"
.br
.RI "Return a positive number if a config line is detected\&. "
.ti -1c
.RI "char ** \fBfill_config_region\fP (\fBt_map\fP *map)"
.br
.RI "Fill the config region of the file\&. "
.ti -1c
.RI "\fBt_map\fP \fBft_check_config\fP (\fBt_map\fP *map)"
.br
.RI "Check if the config is properly formatted or not\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
