.TH "src/settings/ft_settings_hooks.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settings/ft_settings_hooks.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'ft_keys\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include <X11/X\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhook_settings_close_window\fP (void *param)"
.br
.RI "Hook used to close window or set the window size if MACRO Enabled\&. "
.ti -1c
.RI "int \fBhook_settings_handle_keypress\fP (int keycode, void *param)"
.br
.RI "Handle mouse click in the settings window\&. "
.ti -1c
.RI "int \fBhook_settings_handle_mouse_click\fP (int button, int x, int y, void *param)"
.br
.RI "Hook when the mouse is moved while clicking for the settings\&. "
.ti -1c
.RI "int \fBhook_settings_handle_mouse_motion\fP (int x, int y, void *param)"
.br
.RI "Hook when the mouse is moved for the settings\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
