.TH "src/settings/ft_settings_state.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settings/ft_settings_state.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'ft_keys\&.h'\fP
.br
\fR#include 'cub3d\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstate_machine\fP (int keycode, \fBt_mlx\fP *mlx)"
.br
.RI "State machine for the settings window\&. "
.ti -1c
.RI "enum \fBe_screen_size\fP \fBcircle_state\fP (int x, int y)"
.br
.RI "Return an enum according to selected circle using coordinates\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
