.TH "src/ft_utils.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtry_to_open_close_file\fP (char *file_name)"
.br
.RI "Try to open the file specified by file_name\&. "
.ti -1c
.RI "size_t \fBcount_array_length\fP (char **array)"
.br
.RI "Count the number of strings that an array have Should absolutely be NULL-Terminated\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
