.TH "src/generation/gen.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/gen.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'maze\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_map_raoul\fP * \fBcub_new_map_from_dimensions\fP (char *dimensions)"
.br
.RI "Allocates a new map with the given dimension\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
