.TH "src/generation/growing_tree.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/growing_tree.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'maze\&.h'\fP
.br
\fR#include <malloc\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub_growing_tree\fP (\fBt_map_raoul\fP *map)"
.br
.RI "Cub3D Maze Generator, uses dimensions from gen, store them in map and create a random perfect maze\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
