.TH "src/hitwall.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hitwall.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d_render\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhitwall_loop\fP (const \fBt_data\fP *data, \fBt_raydata\fP *rdata)"
.br
.RI "Check which wall will be hit\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void hitwall_loop (const \fBt_data\fP * data, \fBt_raydata\fP * rdata)"

.PP
Check which wall will be hit\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.br
\fIrdata\fP structure to handle important values for rendering 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
