.TH "src/init.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_data\fP * \fBcub_init\fP (\fBt_data\fP *data)"
.br
.RI "Initialize map and backbuffer for rendering\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_data\fP * cub_init (\fBt_data\fP * data)"

.PP
Initialize map and backbuffer for rendering\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP
\fBReturns\fP
.RS 4
t_data* data if successful, NULL otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
