.TH "Keys" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys \- Keys macros
.PP
 \- Regroup all the keys used in the project\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_ESCAPE\fP   65307"
.br
.RI "Keycode for the escape key\&. "
.ti -1c
.RI "#define \fBKEY_ENTER\fP   65293"
.br
.RI "Keycode for the enter key\&. "
.ti -1c
.RI "#define \fBKEY_SPACE\fP   32"
.br
.RI "Keycode for the space key\&. "
.ti -1c
.RI "#define \fBKEY_ARROW_LEFT\fP   65361"
.br
.RI "Keycode for the left key\&. "
.ti -1c
.RI "#define \fBKEY_ARROW_UP\fP   65362"
.br
.RI "Keycode for the up key\&. "
.ti -1c
.RI "#define \fBKEY_ARROW_RIGHT\fP   65363"
.br
.RI "Keycode for the right key\&. "
.ti -1c
.RI "#define \fBKEY_ARROW_DOWN\fP   65364"
.br
.RI "Keycode for the down key\&. "
.ti -1c
.RI "#define \fBKEY_A\fP   97"
.br
.RI "Keycode for the A key\&. "
.ti -1c
.RI "#define \fBKEY_W\fP   119"
.br
.RI "Keycode for the W key\&. "
.ti -1c
.RI "#define \fBKEY_D\fP   100"
.br
.RI "Keycode for the D key\&. "
.ti -1c
.RI "#define \fBKEY_S\fP   115"
.br
.RI "Keycode for the S key\&. "
.ti -1c
.RI "#define \fBKEY_C\fP   99"
.br
.RI "Keycode for the C key\&. "
.ti -1c
.RI "#define \fBKEY_M\fP   109"
.br
.RI "Keycode for the M key\&. "
.ti -1c
.RI "#define \fBKEY_F\fP   102"
.br
.RI "Keycode for the F key\&. "
.ti -1c
.RI "#define \fBKEY_V\fP   118"
.br
.RI "Keycode for the V key\&. "
.ti -1c
.RI "#define \fBKEY_X\fP   120"
.br
.RI "Keycode for the X key\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBe_movement\fP { \fBMV_UP\fP, \fBMV_LEFT\fP, \fBMV_RIGHT\fP, \fBMV_DOWN\fP }"
.br
.RI "Structure used to define the type of movement with directions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Regroup all the keys used in the project\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define KEY_A   97"

.PP
Keycode for the A key\&. 
.SS "#define KEY_ARROW_DOWN   65364"

.PP
Keycode for the down key\&. 
.SS "#define KEY_ARROW_LEFT   65361"

.PP
Keycode for the left key\&. 
.SS "#define KEY_ARROW_RIGHT   65363"

.PP
Keycode for the right key\&. 
.SS "#define KEY_ARROW_UP   65362"

.PP
Keycode for the up key\&. 
.SS "#define KEY_C   99"

.PP
Keycode for the C key\&. 
.SS "#define KEY_D   100"

.PP
Keycode for the D key\&. 
.SS "#define KEY_ENTER   65293"

.PP
Keycode for the enter key\&. 
.SS "#define KEY_ESCAPE   65307"

.PP
Keycode for the escape key\&. 
.SS "#define KEY_F   102"

.PP
Keycode for the F key\&. 
.SS "#define KEY_M   109"

.PP
Keycode for the M key\&. 
.SS "#define KEY_S   115"

.PP
Keycode for the S key\&. 
.SS "#define KEY_SPACE   32"

.PP
Keycode for the space key\&. 
.SS "#define KEY_V   118"

.PP
Keycode for the V key\&. 
.SS "#define KEY_W   119"

.PP
Keycode for the W key\&. 
.SS "#define KEY_X   120"

.PP
Keycode for the X key\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBe_movement\fP"

.PP
Structure used to define the type of movement with directions\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIMV_UP \fP
.TP
\f(BIMV_LEFT \fP
.TP
\f(BIMV_RIGHT \fP
.TP
\f(BIMV_DOWN \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
