.TH "src/main.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Main function of the program\&. Calls only the cub3d function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main function of the program\&. Calls only the cub3d function\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP Number of arguments\&. 
.br
\fIargv\fP Array of arguments\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int Return values of the cub3d function\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
