.TH "src/map_translate.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map_translate.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <malloc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub_translate_map\fP (\fBt_data\fP *data)"
.br
.RI "Convert 2d map string to int vector\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cub_translate_map (\fBt_data\fP * data)"

.PP
Convert 2d map string to int vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP
\fBReturns\fP
.RS 4
int 1 OK, 0 otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
