.TH "src/generation/maze_direction.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/maze_direction.c
.SH SYNOPSIS
.br
.PP
\fR#include 'maze\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmaze_dir_x\fP (int dir)"
.br
.RI "Maze direction on x axis\&. "
.ti -1c
.RI "int \fBmaze_dir_y\fP (int dir)"
.br
.RI "Maze direction on y axis\&. "
.ti -1c
.RI "int \fBmaze_dir_opp\fP (int dir)"
.br
.RI "Maze inverted direction on x and y axis\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int maze_dir_opp (int dir)"

.PP
Maze inverted direction on x and y axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIdir\fP direction 
.RE
.PP
\fBReturns\fP
.RS 4
int value considering maze MACROS 
.RE
.PP

.SS "int maze_dir_x (int dir)"

.PP
Maze direction on x axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIdir\fP direction 
.RE
.PP
\fBReturns\fP
.RS 4
int value considering maze MACROS 
.RE
.PP

.SS "int maze_dir_y (int dir)"

.PP
Maze direction on y axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIdir\fP direction 
.RE
.PP
\fBReturns\fP
.RS 4
int value considering maze MACROS 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
