.TH "src/render/minimap_player.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/minimap_player.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcubmlx_render_minimap_player\fP (\fBt_data\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cubmlx_render_minimap_player (\fBt_data\fP * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
