.TH "src/render/minimap.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/minimap.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcubmlx_render_minimap_player\fP (\fBt_data\fP *data)"
.br
.ti -1c
.RI "void \fBcub_render_minimap\fP (\fBt_data\fP *data)"
.br
.RI "Render the minimap\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cub_render_minimap (\fBt_data\fP * data)"

.PP
Render the minimap\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP

.SS "void cubmlx_render_minimap_player (\fBt_data\fP * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
