.TH "Player" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- Player functions
.PP
 \- Functions used to make the player playable (no-clipping)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsolve_collision_x\fP (\fBt_data\fP *data, float x_vel)"
.br
.RI "Solver of collision on x axis\&. "
.ti -1c
.RI "void \fBsolve_collision_y\fP (\fBt_data\fP *data, float y_vel)"
.br
.RI "Solver of collision on y axis\&. "
.ti -1c
.RI "void \fBresolve_collision_steps\fP (\fBt_data\fP *data, float vel_x, float vel_y)"
.br
.RI "Solver of collision on x and y using steps smaller than 1 unit, To use only when moving faster than 1 unit, when MOVEMENT_SPEED_FWD_BWD >= 1\&.0f or MOVEMENT_SPEED_LEFT_RIGHT >= 1\&.0f\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions used to make the player playable (no-clipping)\&. 


.SH "Function Documentation"
.PP 
.SS "void resolve_collision_steps (\fBt_data\fP * data, float vel_x, float vel_y)"

.PP
Solver of collision on x and y using steps smaller than 1 unit, To use only when moving faster than 1 unit, when MOVEMENT_SPEED_FWD_BWD >= 1\&.0f or MOVEMENT_SPEED_LEFT_RIGHT >= 1\&.0f\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.br
\fIvel_x\fP velocity on x axis 
.br
\fIvel_y\fP velocity on y axis 
.RE
.PP

.SS "void solve_collision_x (\fBt_data\fP * data, float x_vel)"

.PP
Solver of collision on x axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.br
\fIx_vel\fP velocity on x axis 
.RE
.PP

.SS "void solve_collision_y (\fBt_data\fP * data, float y_vel)"

.PP
Solver of collision on y axis\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.br
\fIy_vel\fP velocity on y axis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
