.TH "src/player.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/player.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include 'mlx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcub_player_update\fP (\fBt_data\fP *data)"
.br
.RI "Updates player based on input\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cub_player_update (\fBt_data\fP * data)"

.PP
Updates player based on input\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
