.TH "src/generation/posvec.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/posvec.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <malloc\&.h>\fP
.br
\fR#include 'maze\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_posvec\fP * \fBposvecnew\fP (size_t size)"
.br
.RI "Create a vector with an initial starting size\&. "
.ti -1c
.RI "int \fBposvecpush\fP (\fBt_posvec\fP *vec, \fBt_pos2\fP data)"
.br
.RI "Add a new element to the vector\&. "
.ti -1c
.RI "int \fBposvecpop\fP (\fBt_posvec\fP *vec, \fBt_pos2\fP *pos)"
.br
.RI "Pops the last element of the vector if not empty\&. "
.ti -1c
.RI "int \fBposvecremove\fP (\fBt_posvec\fP *vec, size_t index, \fBt_pos2\fP *result)"
.br
.RI "Removes the element at the specified index from the vector if found\&. "
.ti -1c
.RI "void \fBposvecfree\fP (\fBt_posvec\fP *vec)"
.br
.RI "Free the vector\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
