.TH "PRINT_MACROS" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PRINT_MACROS \- Print macros functions
.PP
 \- Print macros used to print\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRESET\fP   '\\033[0m'"
.br
.ti -1c
.RI "#define \fBRESET_COLOR\fP   \fBRESET\fP"
.br
.ti -1c
.RI "#define \fBBOLD\fP   '\\033[1m'"
.br
.ti -1c
.RI "#define \fBUNDERLINE\fP   '\\033[4m'"
.br
.ti -1c
.RI "#define \fBBLACK\fP   '\\033[30m'"
.br
.ti -1c
.RI "#define \fBRED\fP   '\\033[31m'"
.br
.ti -1c
.RI "#define \fBGREEN\fP   '\\033[32m'"
.br
.ti -1c
.RI "#define \fBYELLOW\fP   '\\033[33m'"
.br
.ti -1c
.RI "#define \fBBLUE\fP   '\\033[34m'"
.br
.ti -1c
.RI "#define \fBPURPLE\fP   '\\033[35m'"
.br
.ti -1c
.RI "#define \fBCYAN\fP   '\\033[36m'"
.br
.ti -1c
.RI "#define \fBWHITE\fP   '\\033[37m'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Print macros used to print\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define BLACK   '\\033[30m'"

.SS "#define BLUE   '\\033[34m'"

.SS "#define BOLD   '\\033[1m'"

.SS "#define CYAN   '\\033[36m'"

.SS "#define GREEN   '\\033[32m'"

.SS "#define PURPLE   '\\033[35m'"

.SS "#define RED   '\\033[31m'"

.SS "#define RESET   '\\033[0m'"

.SS "#define RESET_COLOR   \fBRESET\fP"

.SS "#define UNDERLINE   '\\033[4m'"

.SS "#define WHITE   '\\033[37m'"

.SS "#define YELLOW   '\\033[33m'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
