.TH "src/generation/random.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generation/random.c
.SH SYNOPSIS
.br
.PP
\fR#include 'maze\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_srand\fP (unsigned int seed)"
.br
.RI "Sets the initial random state from the given seed\&. "
.ti -1c
.RI "unsigned int \fBft_rand\fP (void)"
.br
.RI "Generate a random unsigned int\&. "
.ti -1c
.RI "void \fBarray_shuffle\fP (int *arr, int len)"
.br
.RI "Shuffle an array\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
