.TH "src/render/render.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/render.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d\&.h'\fP
.br
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcub_render_sprites\fP (\fBt_data\fP *data, \fBt_raydata\fP *rdata)"
.br
.ti -1c
.RI "void \fBcub_render\fP (\fBt_data\fP *data)"
.br
.RI "Main rendering function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cub_render (\fBt_data\fP * data)"

.PP
Main rendering function\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP

.SS "void cub_render_sprites (\fBt_data\fP * data, \fBt_raydata\fP * rdata)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
