.TH "src/render/render_more.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/render_more.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBraycalc\fP (const \fBt_pos2\fP win_size, int x, float cam_angle, \fBt_raydata\fP *rdata)"
.br
.RI "Function to calculate rays using window size and camera angle\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void raycalc (const \fBt_pos2\fP win_size, int x, float cam_angle, \fBt_raydata\fP * rdata)"

.PP
Function to calculate rays using window size and camera angle\&. 
.PP
\fBParameters\fP
.RS 4
\fIwin_size\fP window size 
.br
\fIx\fP x axis column 
.br
\fIcam_angle\fP camera angle 
.br
\fIrdata\fP structure to handle important values for rendering 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
