.TH "s_args" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_args \- Structure to handle command-line arguments\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBmap\fP"
.br
.ti -1c
.RI "char * \fBgen\fP"
.br
.ti -1c
.RI "int \fBgoal\fP"
.br
.ti -1c
.RI "char * \fBkey_tex\fP"
.br
.ti -1c
.RI "char * \fBdoor_tex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to handle command-line arguments\&. 
.SH "Field Documentation"
.PP 
.SS "char* s_args::door_tex"

.SS "char* s_args::gen"

.SS "int s_args::goal"

.SS "char* s_args::key_tex"

.SS "char* s_args::map"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
