.TH "s_circle" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_circle \- Structure used to store circle informations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ft_draw\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.ti -1c
.RI "int \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store circle informations\&. 
.SH "Field Documentation"
.PP 
.SS "int s_circle::color"

.SS "int s_circle::radius"

.SS "int s_circle::x"

.SS "int s_circle::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
