.TH "s_data" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_data \- Structure used to store the mlx and map structures\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_mlx\fP \fBmlx\fP"
.br
.ti -1c
.RI "\fBt_map\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBt_input\fP \fBinput\fP"
.br
.ti -1c
.RI "\fBt_player\fP \fBplayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store the mlx and map structures\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_input\fP s_data::input"

.SS "\fBt_map\fP s_data::map"

.SS "\fBt_mlx\fP s_data::mlx"

.SS "\fBt_player\fP s_data::player"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
