.TH "s_img" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_img \- Structure used to store an image (buffer that contain image, and size)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBpxls\fP"
.br
.ti -1c
.RI "void * \fBimg\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBmlx_width\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBbits_per_pixel\fP"
.br
.ti -1c
.RI "int \fBendian\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store an image (buffer that contain image, and size)\&. 
.SH "Field Documentation"
.PP 
.SS "int s_img::bits_per_pixel"

.SS "int s_img::endian"

.SS "int s_img::height"

.SS "void* s_img::img"

.SS "int s_img::mlx_width"

.SS "char* s_img::path"

.SS "char* s_img::pxls"

.SS "int s_img::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
