.TH "s_input" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_input \- Structure that handle the input of the player\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBfwd\fP"
.br
.ti -1c
.RI "bool \fBbckwd\fP"
.br
.ti -1c
.RI "bool \fBleft\fP"
.br
.ti -1c
.RI "bool \fBright\fP"
.br
.ti -1c
.RI "bool \fBturn_left\fP"
.br
.ti -1c
.RI "bool \fBturn_right\fP"
.br
.ti -1c
.RI "bool \fBcollision\fP"
.br
.ti -1c
.RI "bool \fBminimap\fP"
.br
.ti -1c
.RI "bool \fBfov\fP"
.br
.ti -1c
.RI "int \fBmouse_input\fP"
.br
.ti -1c
.RI "int \fBskip_next_mouse_input\fP"
.br
.ti -1c
.RI "int \fBdelta_mouse_x\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the input of the player\&. 
.SH "Field Documentation"
.PP 
.SS "bool s_input::bckwd"

.SS "bool s_input::collision"

.SS "int s_input::delta_mouse_x"

.SS "bool s_input::fov"

.SS "bool s_input::fwd"

.SS "bool s_input::left"

.SS "bool s_input::minimap"

.SS "int s_input::mouse_input"

.SS "bool s_input::right"

.SS "int s_input::skip_next_mouse_input"

.SS "bool s_input::turn_left"

.SS "bool s_input::turn_right"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
