.TH "s_map_raoul" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_map_raoul \- Structure to handle the special map needed for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBwalls\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBstart_pos\fP"
.br
.ti -1c
.RI "float \fBstart_angle\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBdoor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to handle the special map needed for rendering\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_pos2\fP s_map_raoul::door"

.SS "size_t s_map_raoul::height"

.SS "\fBt_pos2\fP s_map_raoul::key"

.SS "float s_map_raoul::start_angle"

.SS "\fBt_pos2\fP s_map_raoul::start_pos"

.SS "int* s_map_raoul::walls"

.SS "size_t s_map_raoul::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
