.TH "s_player" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_player \- Structure that handle the player information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_vec2\fP \fBpos\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBfov\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the player information\&. 
.SH "Field Documentation"
.PP 
.SS "float s_player::angle"

.SS "float s_player::fov"

.SS "\fBt_vec2\fP s_player::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
