.TH "s_pos2" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_pos2 \- Structure that handle positions in the map\&. Same as \fBt_coordinates\fP but with signed integers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle positions in the map\&. Same as \fBt_coordinates\fP but with signed integers\&. 
.SH "Field Documentation"
.PP 
.SS "int s_pos2::x"

.SS "int s_pos2::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
