.TH "s_posvec" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_posvec \- Vector implementation that stores \fBt_pos2\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <maze\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_pos2\fP * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector implementation that stores \fBt_pos2\fP objects\&. 
.SH "Field Documentation"
.PP 
.SS "size_t s_posvec::capacity"

.SS "\fBt_pos2\fP* s_posvec::data"

.SS "size_t s_posvec::len"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
