.TH "s_settings" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_settings \- Structure that handle the settings of the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBwin_ptr\fP"
.br
.ti -1c
.RI "enum \fBe_screen_size\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBcircle_yes\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBcircle_no\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the settings of the game\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_img\fP s_settings::background"

.SS "\fBt_img\fP s_settings::circle_no"

.SS "\fBt_img\fP s_settings::circle_yes"

.SS "enum \fBe_screen_size\fP s_settings::state"

.SS "void* s_settings::win_ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
