.TH "s_spritedata" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_spritedata \- Norm-compliant multi-variable holder for math stuff\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_vec2\fP \fBtransform\fP"
.br
.ti -1c
.RI "\fBt_vec2\fP \fBsprite\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBsprite_size\fP"
.br
.ti -1c
.RI "int \fBsprite_screen_x\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBdraw_start\fP"
.br
.ti -1c
.RI "\fBt_pos2\fP \fBdraw_end\fP"
.br
.ti -1c
.RI "\fBt_raydata\fP * \fBrdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Norm-compliant multi-variable holder for math stuff\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_pos2\fP s_spritedata::draw_end"

.SS "\fBt_pos2\fP s_spritedata::draw_start"

.SS "\fBt_raydata\fP* s_spritedata::rdata"

.SS "\fBt_vec2\fP s_spritedata::sprite"

.SS "int s_spritedata::sprite_screen_x"

.SS "\fBt_pos2\fP s_spritedata::sprite_size"

.SS "\fBt_vec2\fP s_spritedata::transform"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
