.TH "s_textures" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_textures \- Structure that handle the textures of the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_img\fP \fBnorth\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBeast\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBwest\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBsouth\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBdoor\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBt_color\fP \fBfloor\fP"
.br
.ti -1c
.RI "\fBt_color\fP \fBceiling\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the textures of the game\&. 
.SH "Field Documentation"
.PP 
.SS "\fBt_color\fP s_textures::ceiling"

.SS "\fBt_img\fP s_textures::door"

.SS "\fBt_img\fP s_textures::east"

.SS "\fBt_color\fP s_textures::floor"

.SS "\fBt_img\fP s_textures::key"

.SS "\fBt_img\fP s_textures::north"

.SS "\fBt_img\fP s_textures::south"

.SS "\fBt_img\fP s_textures::west"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
