.TH "src/render/sprite.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/render/sprite.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include 'data_structure\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcub_render_sprites\fP (\fBt_data\fP *data, \fBt_raydata\fP *rdata)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cub_render_sprites (\fBt_data\fP * data, \fBt_raydata\fP * rdata)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
