.TH "u_color" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_color \- Union used to store color information\&. It can be used to store color in RGBA format or as a separate RGB and alpha values\&. Used for big-endian systems\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBargb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union used to store color information\&. It can be used to store color in RGBA format or as a separate RGB and alpha values\&. Used for big-endian systems\&. 
.SH "Member Function Documentation"
.PP 
.SS "struct u_color::__attribute__ ((packed) )\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "int u_color::argb"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
