.TH "src/math/utils.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/math/utils.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBabsf\fP (float n)"
.br
.RI "Returns the absolute value of a float\&. "
.ti -1c
.RI "int \fBabs\fP (int n)"
.br
.RI "Returns the absolute value of an int\&. "
.ti -1c
.RI "int \fBmax\fP (int a, int b)"
.br
.RI "Returns the highest value between a and b\&. "
.ti -1c
.RI "double \fBmind\fP (double a, double b)"
.br
.RI "Returns the lowest value between doubles a and b\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
