.TH "src/args/validation.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/args/validation.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcub_arg_display_error\fP (int err)"
.br
.ti -1c
.RI "int \fBcub_args_validation\fP (\fBt_args\fP *args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cub_arg_display_error (int err)"

.SS "int cub_args_validation (\fBt_args\fP * args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
