.TH "src/math/vec2.c" 3 "Cub3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/math/vec2.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cub3d_render\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_vec2\fP \fBvec2rotate\fP (\fBt_vec2\fP vec, float angle)"
.br
.RI "Returns a new vector rotated according to the angle\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cub3D from the source code\&.
